### ISSUE TITLE
directory structure mixes infrastructure with contributions

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#113]
`src` contains both core code (e.g. `common`, `wf_utils`) and community-contributed task code. For readability, I'd suggest splitting out core code from contributions. Same within tasks -- datasets, methods, and metrics shouldn't be intermixed with all the other stuff that only task leaders should care about

**Comment by rcannood** [comment]
Can you clarify what you mean by this?

The current task structure is:

    src/
      common/               # core code
      datasets/             # common datasets
      sometask/             # task-specific code
        api/
        methods/
        metrics/
        ...

I made a diagram of the structure as a whole (inspired by the images you made for the upcoming publication): https://main--openproblems.netlify.app/documentation/more_information/project_structure.html.

When adding a method or metric, a contributor only needs to worry about editing code in `src/sometask/methods` or `src/sometask/metrics`.

When adding a common dataset, a contributor does need to add a component to `src/datasets/loaders`. However, I don't think it would make sense to split the data loaders from the components that process the output of the dataset loaders.

We could move all of the tasks into a separate directory `src/tasks`, which would align the structure more to what's being used in the v1 repo:

    src/
      common/               # core code
      datasets/             # common datasets
      tasks/
        sometask/             # task-specific code
          api/
          methods/
          metrics/
          ...

However for the original v2 repository I opted not to put all of the tasks in `src/tasks` but instead simply in `src` since it seems quite clear to me that the `src/common` and `src/datasets` directories are related to core functionality and functionality related to processing datasets, while other folders such as `src/denoising` contain the code for the Denoising task.

**Comment by scottgigante-immunai** [comment]
Currently what I see is:
```
src/
  batch_integration/ # for contributors
  common/ # for core team
  datasets/ # for core team
  denoising/ # for contributors
  dimensionality_reduction/ # for contributors
  label_projection/ # for contributors
  migration/ # for core team
  multimodal_data_integration/ # for contributors
  wf_utils/ # for core team
```
and then within each task
```
task/
  api/ # for task leader
  control_methods/ # for task leader
  methods/ # for contributors
  metrics/ # for contributors
  process_dataset/ # for core team?
  resources_scripts/ # for core team
  resources_test_scripts/ # for core team
  workflows/run/ # for core team
  README.md # for contributors
```

It's unclear just by looking at it that e.g. `migration` is not a task. I'd advocate strongly for separating tasks from other code, and ideally separating components (datasets, methods, metrics) from other code within each task.

**Comment by rcannood** [comment]
Would you prefer this overall project structure, then?

    src/
      common/ # for core team
      datasets/ # for core team
      migration/ # for core team
      tasks/ # for contributors
        batch_integration/
        denoising/
        dimensionality_reduction/
        label_projection/
        multimodal_data_integration/
      wf_utils/ # for core team

Within a task, the `api`, `control_methods` and `process_dataset` will need to be defined by the task leaders. The `resources_scripts` and `workflows/run` folders are things that I expect the task leaders should also be able to maintain, although I agree that the Nextflow code is currently a bit too complicated for that.

However, it's been a while since I last worked on the Nextflow code and with the current structure (with the `api/` files and metadata that is in the config of the components), I should be able to simplify the generalize the code in those workflows quite well. 

Therefore, the task structure should look something like this:

    task/
      api/ # for task leader
      control_methods/ # for task leader
      methods/ # for contributors
      metrics/ # for contributors
      process_dataset/ # for task leader
      resources_scripts/ # for task leader
      resources_test_scripts/ # for task leader
      workflows/run/ # for task leader
      README.md # for contributors

I'd propose the following changes:

- Move tasks from `src/*` to `src/tasks/*`
- Document which folders are part of a tasks leader's responsibilities (part of the upcoming documentation)

**Comment by scottgigante-immunai** [comment]
> Move tasks from src/* to src/tasks/*

+1. This would help a lot.

> Document which folders are part of a tasks leader's responsibilities (part of the upcoming documentation)

Personally I'd rather 
```
  resources_scripts/ # for task leader
  resources_test_scripts/ # for task leader
  workflows/run/ # for task leader
```
all go in a subdirectory called `scripts` or something like that.
