### ISSUE TITLE
Check that `config.yml` arguments and `script.py` par match

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#122]
I got an error because a parameter was not defined in my `par` dict, even though I defined it. I figured it was because I had not defined the corresponding param in `config.vsh.yml`, but this was confusing. better still imo would be if the script didn't define `par`, since this definition is ignored -- instead for example script.py could contain a function taking `par` as an argument.

**Comment by dburkhardt** [comment]
Can you provide code to reproduce?

**Comment by rcannood** [comment]
This is because everything that's between the `## VIASH START` and `## VIASH END` codeblock in the `script.py` is a placeholder, since Viash will remove it and replace it with something else.

While this is already documented, I think it would be better if the `create_component` adds a comment which mentions this concept once more.

**Comment by scottgigante-immunai** [comment]
> Viash will remove it and replace it with something else.

Would it be better just to remove it then? Or at least put in a comment that says "do not edit! this code is regenerated at runtime. to change the script parameters, edit `config.vsh.yml`

**Comment by KaiWaldrant** [comment]
When you want to run your script locally like : `python script.py` you can set your variables locally within the `## VIASH START` and `## VIASH END` . This will not be overwritten then because you do no run it with viash. 

When you want to use it with viash you do not need to delete this code block because it will be replaced with the parameters set in the config file/args/par(ameters) provided in the command.

**Comment by rcannood** [comment]
Exactly. The stuff between `## VIASH START` and `## VIASH END` is just for allowing a developer to execute (parts of) the script during development.

You _can_ remove it, though I find it helpful that it's there so you can debug your code quite easily.

Maybe this'll help you out: if your `par` dictionary is incredibly out of date with what is defined in the Viash config, you can run `viash config inject path/to/config.vsh.yaml`, which will update the `par` dict for you.

**Comment by scottgigante-immunai** [comment]
Let's start by adding a comment in the autogeneration script so it says 
```
## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes in config.vsh.yaml and then run viash config inject config.vsh.yaml
[...]
## VIASH END
```
