### ISSUE TITLE
Test mode for methods

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#124]
Long running methods (e.g. scvi) take a long time to test. In v1 we allow a `test` parameter to e.g. limit the number of iterations / training epochs / etc. Is there an equivalent in v2?

**Comment by rcannood** [comment]
Not yet. Since the example dataset is downsampled, all components currently in v2 can get unit tested in less than 15m ([example](https://github.com/openproblems-bio/openproblems-v2/actions/runs/4950879942), which includes tools like scvi. Hence I didn't put effort in implementing this functionality.

If this ever changes, I'm happy to add in this functionality. As long as it isn't, I think less is more.

**Comment by scottgigante-immunai** [comment]
In my experience from v1, some methods take a very long time to test, even with the test dataset (which was 500 cells). I'm reopening and labelling as `wontfix` for now; if the test runtime changes as we complete the migration we can add back to the milestone.

**Comment by rcannood** [comment]
This issue currently doesn't present itself in the v2. Let's reopen it when there is a component that runs for too long. IMO it doesn't make sense to keep this open if the need for this functionality is not there.
